### ISSUE TITLE
Hiding app bar and removing margin from body

### ISSUE THREAD

**Issue by duggavo** [cogentcore/core#1127] opened 2024-08-12 19:13 UTC
### Describe the feature

add a way to remove, or at least hide, the TopAppBar.

additionally, is it possible to completely remove the padding of the Scene?

**Comment by kkoreilly** [comment] 2024-08-12 19:23
Yes, we are currently working on restructuring the app bar and adding an option to disable it (duplicate of #1074). To remove the padding of the Scene, you can do this:

```go
myWidget.Scene.Styler(func(s *styles.Style) {
  s.Padding.Zero()
})
```

**Closed as completed** 2024-08-22 16:25 UTC
Labels: enhancement
