### ISSUE TITLE
manjaro linux build error

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#911] opened 2024-02-25 19:16 UTC
### Describe the bug

see png

### How to reproduce

run core demo

### Platform

Linux

**Comment by ddkwork** [comment] 2024-02-25 19:17
![{D4F7CA49-4A96-484f-B90A-0E675134464E}.png](https://github.com/cogentcore/core/assets/19886504/d50505d5-f4fb-424d-9c1f-b8c32f378377)

**Comment by kkoreilly** [comment] 2024-02-26 04:31
This is a duplicate of #682, which I will work on fixing soon.

**Closed as completed by kkoreilly** 2024-02-26 04:31 UTC
Labels: bug

**Comment by ddkwork** [comment] 2024-02-27 05:15
> This is a duplicate of #682, which I will work on fixing soon.

I still have some doubts because I successfully installed Vulkan headers at that time, which indicates that the VK driver for Linux systems under VMware is supported. It does not want to install Windows in VMware because VMtools does not provide VK drivers for Windows, while Linux provides Vulkan headers. However, the Vulkaninfo command cannot be found in the terminal. How is the VK driver installed in Linux?

**Comment by kkoreilly** [comment] 2024-02-27 07:05
Even if it says that it has some Vulkan headers, I don't think that VMs can have real Vulkan support. I will look into this more in the context of #682.
