### ISSUE TITLE
Large file size

### ISSUE THREAD

**Issue by SAXN-SYNX** [cogentcore/core#1116] opened 2024-08-05 17:28 UTC
### Describe the bug

Just hello world creates ~20 mb file.
```
`package main

import (
	"cogentcore.org/core/core"
)

func main() {
	win := core.NewBody("My Application")
	core.NewButton(win).SetText("Hello, World !")
	win.RunMainWindow()
}
`
```

### How to reproduce

just build the code with core build.

### Platform

Linux

**Comment by kkoreilly** [comment] 2024-08-05 17:47
This is a duplicate of #733; we will continue to work on reducing binary sizes over time as much as possible.

**Closed as not planned by kkoreilly** 2024-08-05 17:47 UTC
Labels: bug, duplicate
