### ISSUE TITLE
WASM APP does not display Chinese

### ISSUE THREAD

**Issue by wingofsky** [cogentcore/core#1369] opened 2024-12-13 11:24 UTC
### Describe the bug

The Native APP can display Chinese

<img width="867" alt="image" src="https://github.com/user-attachments/assets/67358c63-9cc4-4077-b91a-b1b101ebfcfb" />

WASM APP does not display Chinese

<img width="934" alt="image" src="https://github.com/user-attachments/assets/9aa5126b-1c1e-49c2-9e96-8b01737fe3c9" />

But what's strange is that when WASM loads it shows Chinese

<img width="296" alt="image" src="https://github.com/user-attachments/assets/95d5c4c4-b1a9-41d2-b65c-a74abcee99ca" />

### How to reproduce

See the example code

### Example code

```go
package main

import "cogentcore.org/core/core"

var (
	Body   = core.NewBody()
	Header = core.NewFrame(Body)
)

func main() {
	core.NewText(Header).SetText("1")
	core.NewText(Header).SetText("2")
	core.NewText(Header).SetText("3")
	//core.NewButton(Header).SetText("4")
	//core.NewButton(Header).SetText("5")
	//core.NewButton(Header).SetText("6")

	core.NewButton(Body).SetText("en:Hello, World!")
	core.NewButton(Body).SetText("zh:你好")

	Body.RunMainWindow()
}
```

### Platform

macOS

**Comment by kkoreilly** [comment] 2024-12-15 00:32
Thank you for reporting this. This is a duplicate of #568, which I will try to implement within a few weeks.

**Closed as not planned by kkoreilly** 2024-12-15 00:32 UTC
Labels: bug, duplicate
