### ISSUE TITLE
support non-Latin languages like araibc and direction from right-to-left

### ISSUE THREAD

**Issue by m-abdalrahman** [cogentcore/core#1166] opened 2024-08-21 12:58 UTC
### Describe the feature

When trying to write in Arabic, the letters appear as in the picture, I think that the Arabic language is not supported.
![Screenshot from 2024-08-21 15-16-19](https://github.com/user-attachments/assets/00170946-74a3-4cfb-9fc9-42ec09a45624)

**Comment by kkoreilly** [comment] 2024-08-21 16:38
This is a duplicate of #568, which we will work on relatively soon.

**Closed as not planned by kkoreilly** 2024-08-21 16:38 UTC
Labels: duplicate, enhancement
