### ISSUE TITLE
Add < > stepping buttons (option) to Chooser

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#777] opened 2024-01-09 18:46 UTC
This is particularly important for the date view -- you really want to be able to flip through the months one at a time, instead of pulling down a menu.  Probably not useful enough for the space for other cases, so probably want to make it an option.

**Comment by kkoreilly** [comment] 2024-01-09 20:55
Duplicate of #692.

**Closed as completed by kkoreilly** 2024-01-09 20:55 UTC
Labels: enhancement
