### ISSUE TITLE
surpport i18in?

### ISSUE THREAD

**Issue by itildesk** [cogentcore/core#1396] opened 2024-12-23 21:56 UTC
### Describe the feature

![image](https://github.com/user-attachments/assets/ecd3b223-21ce-4f32-993e-dc2caca97e76)

**Comment by kkoreilly** [comment] 2024-12-23 22:15
Thank you for filing this issue. We are planning to support internationalization; see #568 and #9. We plan to work on those issues within a few weeks; this is a duplicate of those issues.

**Closed as not planned by kkoreilly** 2024-12-23 22:15 UTC
Labels: duplicate, enhancement
